[[chains]]
chain_type="evm"
chain_name="ethereum"
latency=6
commission = 5 # 5% commission rate, if 0, no commission
admin="xxxxxxxx" # use your admin account private key 0xaa..00 (pay gas)
rpc="https://eth-mainnet.g.alchemy.com/<api-key>" # use your own rpc
tokens=["0xdAC17F958D2ee523a2206206994597C13D831ec7", "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"]