name: Build and Push Docker Image

on:
  # Trigger manually from Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., latest, v1.0.0, dev)'
        required: true
        default: 'latest'
  # Trigger on version tags
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/zeropay

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tags
        id: tags
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual trigger - use provided tag
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/zeropay:${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_type }}" = "tag" ]; then
            # Version tag push - extract version
            VERSION=${GITHUB_REF#refs/tags/v}
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/zeropay:latest,${{ secrets.DOCKERHUB_USERNAME }}/zeropay:$VERSION,${{ secrets.DOCKERHUB_USERNAME }}/zeropay:$MAJOR.$MINOR,${{ secrets.DOCKERHUB_USERNAME }}/zeropay:$MAJOR" >> $GITHUB_OUTPUT
          else
            # Fallback
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/zeropay:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        continue-on-error: true
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Output summary
        run: |
          echo "### Docker Build Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image pushed to:** \`${{ steps.tags.outputs.tags }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Platforms:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "**Tag:** ${{ github.event.inputs.tag }}" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ github.ref_type }}" = "tag" ]; then
            echo "**Version:** ${GITHUB_REF#refs/tags/}" >> $GITHUB_STEP_SUMMARY
          fi
